### ISSUE TITLE
Question: Method not found

### ISSUE THREAD

**Issue by dave4you** [Astn/JSON-RPC.NET#100]
Hi,

I used the example code to try and get my own service up and running.

I am passing {"method": "helloworld", "params": ["lovely"], "id": 10}
The result however is:
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":"The method does not exist / is not available."},"id":10}

Could anyone help me and tell me what I am doing wrong?

Much appreciated,

Dave

----code below----
[MyCode.txt](https://github.com/Astn/JSON-RPC.NET/files/2544148/MyCode.txt)

**Comment by Astn** [comment]
Glad you got it working!

**Comment by Astn** [comment]
Do you have it working over sockets? There are a few examples on the wiki.
For the http hosting, what framework are you using for http? 
There is an asp.net adapter I created a few years ago, you could likely adapt the code from it for the framework you are using.

**Comment by Astn** [comment]
> Does it only work with Mono or also with Kestrel?

The nuget package only works with mono on linux, but that's mostly just because the project / nuget changes to get it to work on dotnet core have not been merged in.
If you want it to work on dotnet core today, then you will need to clone the repo, and go through the process of fixing some of the imports as some of them are different, but that was the only change . 
I do have a branch where I did that work, and also started down the path of a total refactor. Shooting for more speed and pluggable json serializers. https://github.com/Astn/JSON-RPC.NET/pull/90 There are more things I want to do on that branch so just use it as a reference if that is the path you want to take.
>  I was in the understanding that the sockets and http could coexist in the same environment.

I think you could do this. You just need to make sure your continuations or callbacks are sending messages to the correct tcp/http channel, but you need to do that with Sockets or HTTP anyway... So I'm not thinking about any issues.

**Comment by dave4you** [comment]
Great! Thanks for the reply. I will need some time to investigate. I will let you know about the next steps somewhere in the upcoming month. Cheers, Dave

Mobiel geschreven. Kort maar niet onvriendelijk.

________________________________
Van: Austin Harris <notifications@github.com>
Verzonden: donderdag, november 15, 2018 7:44 AM
Aan: Astn/JSON-RPC.NET
CC: D.J. Hoogendoorn (Dave) | openAware BV; State change
Onderwerp: Re: [Astn/JSON-RPC.NET] Question: Method not found (#100)


Does it only work with Mono or also with Kestrel?

The nuget package only works with mono on linux, but that's mostly just because the project / nuget changes to get it to work on dotnet core have not been merged in.
If you want it to work on dotnet core today, then you will need to clone the repo, and go through the process of fixing some of the imports as some of them are different, but that was the only change .
I do have a branch where I did that work, and also started down the path of a total refactor. Shooting for more speed and pluggable json serializers. #90<https://github.com/Astn/JSON-RPC.NET/pull/90> There are more things I want to do on that branch so just use it as a reference if that is the path you want to take.

I was in the understanding that the sockets and http could coexist in the same environment.

I think you could do this. You just need to make sure your continuations or callbacks are sending messages to the correct tcp/http channel, but you need to do that with Sockets or HTTP anyway... So I'm not thinking about any issues.
