### ISSUE TITLE
"method not found" error in release version

### ISSUE THREAD

**Issue by 4nd3250n** [Astn/JSON-RPC.NET#47]
If I publish my web service, and therefore also build in release mode I get the following error.
Each method call returns "Method not found" error.

{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":"The method does not exist / is not available."},"id":1}

Why is this so?

**Comment by 4nd3250n** [comment]
This is urgent !

**Comment by Astn** [comment]
What does the code look like where you are creating your service?

**Comment by jonathancrozier** [comment]
I also have this issue. The code for registering the service looks like this:

`private static object[] _services = new object[] { new ProductsService() };`

The service methods ok are found when in Debug mode, but not when running in Release mode. It is a Windows Service application that I am developing.

Please can you advise?

**Comment by Astn** [comment]
Is there a service Init function that you can override that is part of the windows service life cycle?

**Comment by jonathancrozier** [comment]
Thanks for the reply Austin.

I figured out that it was due to Release mode optimisations. The services weren't being initialised since they technically weren't being used at that point in the code.

I added a static constructor to the class containing the code in my previous comment to force the services to initialise.
